### ISSUE TITLE
In Items view, update the link so it points to itself rather than PDF file that no longer exists

### ISSUE THREAD

**Issue by PaulCongdon** [jlm/maint#67]
In the items view, we have a link associated with the item that points to a PDF file version of the request.  These PDF files are no longer being generated and it would be more useful if the link pointed to itself so we can 'cut-and-paste' the item title with link into an agenda page on Wordpress or other uses.

The itemlink helper in helpers/application_helper.rb should be slightly modified to provide the item index instead of the item number.  Then the REQ_URL environment variable in the .env file should be updated to point to the item instead of the PDF file location on 802.1 file server.  Perhaps the REQ_URL should look like this (depending on whether it is production or staging):

REQ_URL="https://www.802-1.org/items/%s"

**Comment by jlm** [comment]
I'll leave the issue open until the build gets deployed with the necessary environment change.

**Comment by jlm** [comment]
The change has been made in the deployment code.
